### PR TITLE
Added `host` options to Jaeger UDP reporter

### PR DESCRIPTION
**Pull request by matieux**
`localhost` as host by default

### CODE REVIEW

**Comment by StarpTech** [comment]
Hi @matieux thanks for the PR. Could you test it?

**Comment by matieux** [comment]
Hmmm, it's just option parsing... Not sure how I can test it:
1) Need a running Jaeger instance
2) How to 'read' from Jaeger response that it uses the specified host?

**Comment by StarpTech** [comment]
I mean you should test that the tracer is still working. Start jaeger instance with docker and run `./examples/monitoring/jaeger.js`

**Comment by StarpTech** [comment]
Hint: It could take some time before you see the first trace.

**Comment by StarpTech** [comment]
I checked it, LGTM

**Pull request merged**
