### PR TITLE
Fix events

### PR DESCRIPTION
**Pull request by NAlexandrov**

### CODE REVIEW

**Comment by StarpTech** [comment]
Hi @NAlexandrov this is already fixed.

**Comment by NAlexandrov** [comment]
No. I added a returned type. For use hemera.on(...).on(...)

**Comment by StarpTech** [comment]
But `on()` doesn't return the instance. See https://nodejs.org/api/events.html#events_emitter_on_eventname_listener

**Comment by NAlexandrov** [comment]
But it's works:
```
hemera
  .on('clientPreRequest', () => console.log('clientPreRequest'))
  .on('clientPostRequest', () => console.log('clientPostRequest'))
  .on('serverPreHandler', () => console.log('serverPreHandler'))
  .on('serverPreRequest', () => console.log('serverPreRequest'))
  .on('serverPreResponse', () => console.log('serverPreResponse'))
  .on('serverResponseError', error => console.error('serverResponseError', error.toString()))
  .on('clientResponseError', error => console.error('clientResponseError', error.toString()));
```

**Comment by StarpTech** [comment]
Sure, because hemera inherits from `eventemitter` but you can't do `hemera.on().add()` and this will break the types.

**Pull request closed without merging**
