### PR TITLE
Update Hapi Dependencies 

### PR DESCRIPTION
**Pull request by jackieluc**
Hi @StarpTech,

The following `hapi` packages have been deprecated and have been migrated under the `hapi` organization. I thought it would be great to migrate them (so they continue to be supported) and update the dependencies.

| Old Version | New Version | Notes |
| :-: | :-: | :- |
| code v^4.1.0 | @hapi/code v^6.0.0 | |
| hoek v4.2.x | @hapi/hoek v8.3.x | |
| heavy v4.0.x | @hapi/heavy v6.2.x | Updated respective config schema, API, and tests |
| joi v^12.0.0 | @hapi/joi v^15.1.1 | I decided not to upgrade to v16 because v16 has breaking changes that require a lot of effort and complexity to upgrade: https://github.com/hapijs/joi/issues/2037 |

I also bumped the versions of each of the following packages that were affected by a minor version (following semver). Please advise if you'd like things to be different.

- nats-hemera v7.1.0
- hemera-joi v6.1.0
- hemera-jwt-auth v6.1.0
- hemera-mail v5.1.0
- hemera-slackbot v5.1.0
- hemera-store v2.1.0

### CODE REVIEW

**Comment by jackieluc** [comment]
The Travis CI has failed due to dependency updates using new features of JavaScript that aren't supported in Node 6. Should we consider dropping support for Node 6 as it reached end of life on 2019-04-30? https://github.com/nodejs/Release#release-schedule

**Comment by momiller121** [comment]
@jackieluc - dropping Node6 support was one of starptech's stated goals.

**Comment by StarpTech** [comment]
Hi @jackieluc thank you for the PR. This PR can't be merged as long as we support Node.js 6 which will introduce a breaking change.

**Comment by momiller121** [comment]
@starptech - if we resubmit this PR with node 6 removed, is this a helpful contribution towards hemera@8? We're open to being coached / advised how we can best contribute. Thank you.

**Comment by StarpTech** [comment]
This PR hasn't a single purpose. There are too many breaking changes. Please create several PR's.

> if we resubmit this PR with node 6 removed, is this a helpful contribution towards hemera@8? We're open to being coached / advised how we can best contribute. Thank you.

Yes, if it really contains only a dependency update. I will create a branch called `next` which prepares for the next major version.

**Comment by jackieluc** [comment]
Its my bad for making a PR without checking Node 6 support first - though it seems like the migrated Hapi dependencies do not support Node 6. I agree that this PR would be more productive if it were to be included in the next major version of Hemera that drops support for unsupported Node versions.

**Comment by momiller121** [comment]
Hello @StarpTech - I propose that this is a singular purpose PR based on the following rationale: This PR resolves all @hapi family component deprecation warnings. (Dropping of Node6 support is also implied to affect this.) Otherwise, the existing functional contract is unchanged. 

So, breaking change for dropping Node6 - yes. Otherwise, no breaking change.   

And, in a subsequent PR, we'll add Node@12 support (though I have not even looked at that yet).

**Comment by StarpTech** [comment]
@momiller121 that's not correct. Following changes are breaking changes beside to support new hapi modules:

- https://github.com/hemerajs/hemera/pull/243/files#diff-35a4dcf81cd0bfa2339c4a690ea51086R93
- https://github.com/hemerajs/hemera/pull/243/files#diff-793650312af28ef0a6411409aae89304R44

@jackieluc please create different PR's for that and merge against `next` not master.

**Comment by momiller121** [comment]
@StarpTech - I see that now. Thank you. We'll reformulate against the next branch.

**Comment by StarpTech** [comment]
I really appreciate that PR but I think it's not worth it. I will update all dependencies in a batch. In the next days, I will assign several issues to the milestone `Hemera 8 Pheonix`. Feel free to pick one :relaxed:

**Pull request closed without merging**
