### PR TITLE
Prettier globs should be surrounded by double-quotes

### PR DESCRIPTION
**Pull request by pward123**
Prettier globs should be surrounded by double-quotes per 
https://github.com/prettier/prettier/blob/master/README.md#cli

### CODE REVIEW

**Comment by StarpTech** [comment]
Could you test it on windows?

**Comment by pward123** [comment]
Sure, but it may take me a couple of days to get to it. I'll have to put together a windows dev system.

**Comment by StarpTech** [comment]
I can test it for you.

**Comment by StarpTech** [comment]
The scripts have been changed. I updated all commands with double-quotes. Thank you.

**Pull request closed without merging**
